### ISSUE TITLE
Build failed for ubuntu 20.04.5 with exit status 2

### ISSUE THREAD

**Issue by just-hms** [thatisuday/go-cross-build#10]
The project used to build correctly previously on github actions and correctly build locally (using both windows and wsl). 
Unfortunately now it doesn't build anymore.

this is my go.mod

```go
module jim

go 1.19

require gorm.io/gorm v1.22.5

require (
	github.com/jinzhu/inflection v1.0.0 // indirect
	github.com/jinzhu/now v1.1.4 // indirect
	github.com/mattn/go-colorable v0.1.9 // indirect
	github.com/mattn/go-isatty v0.0.14 // indirect
	github.com/mattn/go-sqlite3 v1.14.5 // indirect
)

require (
	github.com/fatih/color v1.13.0
	golang.org/x/sys v0.1.0 // indirect
	gorm.io/driver/sqlite v1.1.4
)
```

this is the github yaml

```yaml
name: release

on:
  release:
    types:
      - created

jobs:

  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate build files
        uses: thatisuday/go-build-action@v1.0.2
        with:
          platforms: "windows/amd64, linux/amd64, darwin/amd64"
          package: ""
          name: "jim"
          compress: "true"
          dest: "dist"
          ldflags: "\"-X 'jim/utils.Version=${{ github.ref_name }}'\""

      - name: Copy build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./dist/*.tar.gz"
```

this is the action's output

![image](https://user-images.githubusercontent.com/57114674/200585118-82596389-1696-49bc-bda8-e523c5a82bcb.png)

thanks in advance.
