### ISSUE TITLE
Cannot find GOROOT directory: /home/runner/work/cyb3rko/MyProject

### ISSUE THREAD

**Issue by cyb3rko** [thatisuday/go-cross-build#3]
I'm receiving the following error:
`go: cannot find GOROOT directory: /home/runner/work/cyb3rko/DiscordCacheExtractor`

What am I missing here?
Do I somehow have to define the goroot path?

**Comment by lukaszraczylo** [comment]
I spent quite a few builds on trying to debug it, kicked in after I specified _all_ the parameters 

```yaml
      - name: Compile binary
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: linux/amd64,darwin/amd64,windows/amd64,linux/arm64,darwin/amd64
          name: semver-gen
          package: ./
          compress: false
          dest: dist
 ```
