### ISSUE TITLE
Relative path for dest is diffucult to work with.

### ISSUE THREAD

**Issue by RonanMacF** [thatisuday/go-cross-build#6]
Relaytive to what working directory?
```
# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            package: 'cmd/<pkg>'
            name: 'program'
            compress: 'true'
            dest: 'dist'
```
Is what I am using but after it runs successfully I don't see any dist folder. What I expect is a dist folder to be in the repo with the three platforms compressed in it. Instead I don't see anything. I have tried variations of `..`, `../dist`, `.` and nothing makes them appear
